//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad_Libardo_Torres.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bibliotecaEntities1 : DbContext
    {
        public bibliotecaEntities1()
            : base("name=bibliotecaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<autores> autores { get; set; }
        public virtual DbSet<bibliotecas> bibliotecas { get; set; }
        public virtual DbSet<libros> libros { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
