//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad_Libardo_Torres.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class libros
    {
        public int libro_id { get; set; }
        public string titulo { get; set; }
        public Nullable<int> paginas { get; set; }
        public Nullable<int> año { get; set; }
        public int autor_id { get; set; }
    
        public virtual autores autores { get; set; }
    }
}
